# Generated by Django 2.2.3 on 2019-07-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_commercebenefit_commercebenefittype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercebenefit',
            name='expiration',
            field=models.DateTimeField(null=True),
        ),
    ]
