# Generated by Django 2.2.3 on 2019-07-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190709_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercebenefittype',
            name='code',
            field=models.CharField(default='just_once', max_length=255),
            preserve_default=False,
        ),
    ]
