# Generated by Django 2.2.3 on 2019-07-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_commerceuserbenefit_commerceuserbenefitstatus'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='commerceuserbenefit',
            index_together=set(),
        ),
        migrations.AddConstraint(
            model_name='commerceuserbenefit',
            constraint=models.UniqueConstraint(fields=('benefit', 'user', 'status'), name='commerce_user_benefit'),
        ),
    ]
