# Generated by Django 2.2.3 on 2019-07-09 23:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20190709_2027'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commerceuserbenefit',
            name='commerce_user_benefit',
        ),
        migrations.AlterIndexTogether(
            name='commerceuserbenefit',
            index_together={('benefit', 'user', 'status')},
        ),
    ]
